Move Parking Flows to Production
cityofaustin/atd-prefect pull request #8
Opened 2022-04-25 22:12 UTC by Charlie-Henry

Moving my feature branch to production. Currently is running under the `parking` project and under the `staging` environment on `atd-data02`. This is also running on a docker imaged based in production [atd-parking-data](https://github.com/cityofaustin/atd-parking-data).

https://cloud.prefect.io/project/ebadfdd9-64b8-4bd8-9e85-1898811eebd9

- Adds parking_data_reconciliation.py which downloads the parking transactions data from the S3 bucket and compares them before uploading to Socrata.
- Adds some more code to atd_parking_data_meters_txn_history.py to support getting PARD data from Smartfolio and Passport (app) data. 
- Each flow now pulls the latest docker container as a task before running the rest of the flow.

Part of this effort:
- https://github.com/cityofaustin/atd-data-tech/issues/8945

Bug Fixes/Issues associated:
- https://github.com/cityofaustin/atd-data-tech/issues/8647
- https://github.com/cityofaustin/atd-data-tech/issues/7696
- https://github.com/cityofaustin/atd-data-tech/issues/8813

2022-04-27 14:21 UTC, frankhereford requested changes
This looks great, but can you please zap the two `.DS_Store` files? They are little extended attribute storage files that macs sometimes litter everywhere. 🚮 Other than that, this is 🚢 💯 

Your flows looks awesome, and I'll be referring to them both today in my own work. 

⚠️ I have not personally tested the flows, only reviewed the code. Please let me know if you want me to get it running locally, I'd be happy to.

2022-04-28 12:34 UTC, frankhereford approved these changes

2022-04-29 19:34 UTC, mateoclarke approved these changes
🚢 💨 ✨

2022-05-31 22:28 UTC, Charlie-Henry commented
I am having problems with moving one of my more straight forward flows into `production`. @chiaberry helped do some investigation into finding why it keeps referencing `staging`. Maybe we break from the template we have, we will have to discuss at a future Prefect Sync. 

https://github.com/cityofaustin/atd-prefect/pull/12#issuecomment-1131902367

2022-07-13 17:18 UTC, merged